#!/usr/bin/env python

import argparse
import io
from google.cloud import vision


def perform_recognition(file):
    vision_client = vision.Client()

    with io.open(file, 'rb') as image_file:
        content = image_file.read()
        image = vision_client.image(content=content)

    labels = image.detect_labels()

    print('Labels:')
    for label in labels:
        print(label.description)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="""Perform image recognition on a specified file""")
    parser.add_argument('file', help='Image path')
    args = parser.parse_args()
    perform_recognition(args.file)
